### ISSUE TITLE
When will this project support Swift 4?

### ISSUE THREAD

**Issue by donly** [helje5/dockSwiftOnARM#1]
I like this project, hope it will upgrade to Swift 4 from 3.
Thank you.

**Comment by helje5** [comment]
Swift 4 doesn't build on ARM yet (help is appreciated, join swift-arm if you think you might be able to). I think Uraimo did a build w/o SPM, we could dockerize that, but I'm not sure how useful that would be. (that would be more useful in combination w/ the [x-toolchain](https://github.com/AlwaysRightInstitute/swift-mac2arm-x-compile-toolchain) as you could use the SPM on macOS)

**Comment by helje5** [comment]
i guess we have a 4.1 alpha branch now

**Comment by yaokantv** [comment]
Wow, that sounds exciting.

**Comment by helje5** [comment]
OK, small update for those not on the swift-arm Slack: There is a 4.1-final Docker now, based on the Swift 4.1 Raspi drop by @chnmrc. I uploaded that to Dockerhub: https://hub.docker.com/r/helje5/rpi-swift/ (and rpi-swift-dev for the image w/ Emacs and other dev tools).

*BUT*: This is NOT considered a stable Raspi build, e.g. it pretty quickly crashes when using Codable, presumably on other stuff too.

Summary: Raspi 4.1 support is getting a *little* forward, but is still far from being complete. Please join the swift-arm Slack if you think you can help w/ fixing issues!!!

**Comment by helje5** [comment]
OK, I think we can close this. Thanks to the swift-arm community we seem to have pretty good Swift 4.1 builds for arm and arm64v8 now.
